name: "Update Angular Action"
permissions:
  contents: read
  pull-requests: write
on: # when the action should run. Can also be a CRON or in response to external events. see https://git.io/JeBz1
  schedule:
    - cron: "30 5 * * 3"
  workflow_dispatch:

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies # the magic happens here !
        uses: fast-facts/ng-update@7840d6c5dfb881a162e7d49a7c4517d3943e25d0 # v1
        with:
          base-branch: main
          repo-token: ${{ secrets.GITHUB_TOKEN }}
